default_language_version:
  python: python3.11

repos:
  # -------------------------------
  # Official Pre-Commit Hooks
  # -------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # -------------------------------
  # Black (formatter)
  # -------------------------------
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # -------------------------------
  # Isort (imports sorter)
  # -------------------------------
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # -------------------------------
  # Pyupgrade (modernize syntax)
  # -------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]

  # -------------------------------
  # Flake8 (linter clássico)
  # -------------------------------
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8

  # -------------------------------
  # Ruff (linter + formatter rápido)
  # -------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
      - id: ruff-format

  # -------------------------------
  # MIME - Type Checking
  # -------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  # -------------------------------
  # Prettier (JS/TS/Markdown/YAML etc.)
  # -------------------------------
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
